<h2>ShortURL</h2>
<p>
	is an <a href="http://opensource.org/licenses/MIT">open source</a>
	link-shortening-Service.
</p>
<p>
	<span class="shorturl">ShortURL</span> allows users to shorten URLs and get
	detailed informations about their usage by the community.
</p>
<p>
	URLs can be shortened either via web-interface or SOAP-Service. So
	integration into your environment should be fairly easy.
</p>
<p>
	<span class="shorturl">ShortURL</span> also eases collaboration on shortened
	URLs as all shortened URLs are assigned to a group you can invite other users
	to.
</p>
<p>
	Extended click-statistiks can be downloaded for later analysis in your
	favourite evaluation-tool and in future can be displayed in the browser
</p>
<p>
	The information retrieved by <span class="shorturl">ShortURL</span> to
	generate the click-statistic can be anonymized via configuration to conform
	to german law regulations (See <a href="http://??">Anonymization</a>)
<p>
	<span class="shorturl">ShortURL</span> is based on open source-software
	like <ul>
	<li><a href="http://framework.zend.com">Zend Framework v1</a> and</li>
	<li><a href="http://doctrine-project.org">Doctrine v2</a></li>
	</ul>
</p>
