<!DOCTYPE html>
<html>
	<head>
		<base href="/<?php echo $this->baseUrl(); ?>"/>
		<?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
	</head>
	<body>
		<?php echo $this->render('header.phtml'); ?>
		<?php echo $this->navigation(); ?>
		<div id="content">
		<?php echo $this->layout()->content; ?>
		</div>
		<?php echo $this->render('footer.phtml'); ?>
    <?php echo $this->headScript() ?>
	</body>
</html>
